baseURL = "file:///Users/MattMcElhannon/Documents/Sites/mattmcelhannon-dot-com/public/"
title = "Matt McElhannon"
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Matt McElhannon"
  description = "Writer. Producer. Fun Guy."
  avatar = "img/avatar.jpg"
  menu_item_separator = " - "
  [[params.social]]
    icon = "youtube"
    name = "YouTube"
    url = "https://www.youtube.com/c/MattMcElhannon"
  [[params.social]]
    icon = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/mattmcelhannon/"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/mattmcelhannon"          
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/mattmcelhannon"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/mattmcelhannon/"    
  [params.style]
   darkestColor = "#dc322f"
   darkColor = "#000000"
   lightColor = "#93a1a1"
   lightestColor = "#eee8d5"
   primaryColor = "#fdf6e3"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
